### ISSUE TITLE
Sites behind VPN are not accessible by sitespeed

### ISSUE THREAD

**Issue by kobolcs** [sitespeedio/sitespeed.io-docker#15]
In linux container of Docker for Windows, I get these errors for behind VPN remote company sites/IPs. In Windows host, the OpenVpn client is used. I can ping,curl IP from any image {tried from busybox,ubuntu docker images} but sitespeed which gaves me this:
docker run --shm-size=4g  -v /c:/sitespeed.io sitespeedio/sitespeed.io http://yy.xx.com -n 1  --net=host
Google Chrome 69.0.3497.100 Mozilla Firefox 62.0
[2018-10-15 07:17:42] INFO: Versions OS: linux 4.9.93-linuxkit-aufs nodejs: v8.12.0 sitespeed.io: 7.5.0 browsertime: 3.7.1 coach: 2.3.0
[2018-10-15 07:17:42] INFO: Starting chrome for analysing http://yy.xx.com 1 time(s)
[2018-10-15 07:17:42] INFO: Testing url http://yy.xx.com iteration 1
[2018-10-15 07:17:46] ERROR: UrlLoadError: Failed to load/verify http://yy.xx.com uri:chrome-error://chromewebdata/
    at SeleniumRunner.loadAndWait (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:200:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Why?

**Comment by soulgalore** [comment]
Hi @kobolcs I think `--net=host` doesn't always seems to work with browsers since they have their own DNS setup etc (at least Firefox). I think you can check Selenium forums to see if they have a hack using VPN from their Docker containers. The same solutions should work here.

Best
Peter

**Comment by kobolcs** [comment]
If anyone is interested , the right answer for my situation, I still don't know why but: use the IP number instead of the hostname and for some sites --dns=targetIPaddress --publish=all is needed. 
Works: `docker run --shm-size=1g --rm -v /c:/sitespeed.io sitespeedio/sitespeed.io https://10.x.x.28/news`
Error :`docker run --shm-size=1g --rm -v /c:/sitespeed.io sitespeedio/sitespeed.io https://www.mysite.com/news`

**Comment by soulgalore** [comment]
Thank you @kobolcs for sharing! I'll close the issue now.
