### ISSUE TITLE
Multiple continuous run lead to hanging containers

### ISSUE THREAD

**Issue by finkinfridom** [sitespeedio/sitespeed.io-docker#17]
Starting from this page: https://www.sitespeed.io/documentation/sitespeed.io/continuously-run-your-tests/ we built a linux server which schedule concurrent `docker run` commands to test several websites.
When the server is freshly rebooted, the number of running containers seems stable.
After a while the system pressure starts growing and containers logs browser failures which lead to hanging running containers for hours (even days).
Here are some logs we collected so far:
```
[2019-09-26 07:28:48] INFO: Running tests using Chrome - 3 iteration(s)
[2019-09-26 07:29:26] INFO: Browser failed to start, trying one more time: Failed to start browser in 60 seconds.
[2019-09-26 07:29:49] INFO: Browser failed to start, trying one more time: Failed to start browser in 60 seconds.
[2019-09-26 07:30:29] INFO: Browser failed to start, trying one more time: Failed to start browser in 60 seconds.
[2019-09-26 07:30:49] INFO: Browser failed to start, trying one more time: Failed to start browser in 60 seconds.
[2019-09-26 07:31:50] INFO: Browser failed to start, trying one more time: Failed to start browser in 60 seconds.
[2019-09-26 07:31:51] INFO: Browser failed to start, trying one more time: Failed to start browser in 60 seconds.
[2019-09-26 07:31:51] ERROR: BrowserError: Could not start the browser with 3 tries
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:82:13)
```
```
[2019-09-26 08:12:43] ERROR: No data to collect
[2019-09-26 08:12:44] ERROR: TypeError: Cannot set property '_meta' of undefined
    at Object.addMetaToHAR (/usr/src/app/node_modules/browsertime/lib/support/har/index.js:138:34)
    at addExtraFieldsToHar (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:76:19)
    at Engine.runByScript (/usr/src/app/node_modules/browsertime/lib/core/engine/index.js:189:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2019-09-26 08:12:45] INFO: Changing network interfaces needs sudo rights.
```

**Comment by soulgalore** [comment]
Hi @finkinfridom can you share a little more how you run (thinking if there's some configuration that can cause it)? How many containers do you run at the same time? Do you run on both Firefox & Chrome?

Best
Peter

**Comment by finkinfridom** [comment]
hey @soulgalore we run batches of 35 docker images per 2 browsers, meaning we have concurrently 70 docker run commands at the same time.
We're investigating whether shifting the start of the execution by some minutes.
Do you have any other suggestion?
