### ISSUE TITLE
Chrome isn't working for webcoach container

### ISSUE THREAD

**Issue by onnimonni** [sitespeedio/sitespeed.io-docker#9]
I tried to run webcoach in OSX `ver: 10.11.6 (15G1004)` with docker for mac `ver: Version 1.12.1 (build: 12133)` but it fails.

When I use firefox instead it works just fine.

Here's the output:
```
$ docker run --rm sitespeedio/coach webcoach https://www.sitespeed.io -b chrome
Sun Nov  6 19:30:28 UTC 2016
ChromeDriver 2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b)
Google Chrome 49.0.2623.75
Mozilla Firefox 45.0
Starting Xvfb ...
Error running advice:  Error: Failed to start browser in 30 seconds.
    at SeleniumRunner.startBrowser (/usr/lib/node_modules/webcoach/node_modules/browsertime/lib/core/seleniumRunner.js:34:11)
    at SeleniumRunner.start (/usr/lib/node_modules/webcoach/node_modules/browsertime/lib/core/seleniumRunner.js:38:25)
    at runIteration (/usr/lib/node_modules/webcoach/node_modules/browsertime/lib/core/engine.js:100:21)
    at Promise.reduce.promise.browserScripts (/usr/lib/node_modules/webcoach/node_modules/browsertime/lib/core/engine.js:162:27)
    at tryCatcher (/usr/lib/node_modules/webcoach/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/usr/lib/node_modules/webcoach/node_modules/bluebird/js/release/reduce.js:147:18)
    at Object.gotAccum (/usr/lib/node_modules/webcoach/node_modules/bluebird/js/release/reduce.js:134:25)
    at Object.tryCatcher (/usr/lib/node_modules/webcoach/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/webcoach/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/usr/lib/node_modules/webcoach/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromiseCtx (/usr/lib/node_modules/webcoach/node_modules/bluebird/js/release/promise.js:597:10)
    at Async._drainQueue (/usr/lib/node_modules/webcoach/node_modules/bluebird/js/release/async.js:131:12)
    at Async._drainQueues (/usr/lib/node_modules/webcoach/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/webcoach/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by soulgalore** [comment]
Hey @onnimonni 
thanks for the report! One thing that is not the best thing with our Chrome containers is that you need to run it with <code>--privileged</code> to get it to work.  Can you try that? Also seen that we haven't updated in in a while, I'll make sure we push a new one per release.

Best
Peter

**Comment by soulgalore** [comment]
Seen I've missed that in the docs, sorry!

**Comment by soulgalore** [comment]
@onnimonni pushed the latest and greatest now. Checkout the [README](https://hub.docker.com/r/sitespeedio/coach/) before you run, I've changed so we follow the standard we have in sitespeed.io/browsertime: you don't need to add the program name, just the parameters.

**Comment by onnimonni** [comment]
After pulling the new image I ran:

```
$ docker run --privileged --rm sitespeedio/coach https://www.sitespeed.io -b chrome
```

and it works brilliantly!

Thanks @soulgalore.
